# Site settings
title: Alex Sharpe
tagline: ~
description: Software Engineer
image: /assets/images/site-image.png
url: https://meebuhs.github.io
github_url: https://github.com/meebuhs
author: Alex Sharpe
lang: en-AU
logo: /favicon.png

# Build settings
remote_theme: meebuhs/arco
plugins:
  - jekyll-sitemap
